name: C++ CI Tests

on:
  push:
    branches: ["cheesedom", "develop"]
  pull_request:
    branches: ["cheesedom", "develop"]

jobs:
  build-and-test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4

    - name: Configure CMake
      run: >
        cmake -B build -S .
        -DCMAKE_BUILD_TYPE=Release
        -DENABLE_TESTING=ON
      
    - name: Build tests
      run: cmake --build build --config Release

    - name: Run CTest
      run: ctest --test-dir build --build-config Release --output-on-failure -j